# Generated by Django 2.1 on 2018-08-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180816_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='choice', to='quiz.Question'),
        ),
    ]
