# Generated by Django 2.1 on 2018-08-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180824_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(blank=True, to='quiz.Question', verbose_name='Questions'),
        ),
    ]
