# Generated by Django 2.1 on 2018-08-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20180824_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
