# Generated by Django 2.1 on 2018-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20180825_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='process',
            field=models.CharField(choices=[('ADD', 'Simple addition'), ('AVG', 'Average')], default='ADD', max_length=100),
        ),
        migrations.AddField(
            model_name='score',
            name='final',
            field=models.IntegerField(default=0),
        ),
    ]
