# Generated by Django 2.1 on 2018-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20180826_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='final',
            field=models.FloatField(default=0),
        ),
    ]
