# Generated by Django 2.1 on 2018-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20180829_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='tally',
        ),
        migrations.AddField(
            model_name='result',
            name='avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='raw_so_far',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='users_tally',
            field=models.IntegerField(default=0),
        ),
    ]
