# Generated by Django 2.1 on 2018-08-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20180830_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScaleQuestion',
        ),
        migrations.AddField(
            model_name='quiz',
            name='layout',
            field=models.IntegerField(choices=[(1, 'Horizontal'), (2, 'Vertical')], default=1, verbose_name='Layout for questions'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg',
            field=models.FloatField(default=0, verbose_name='Average score for this result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='raw_so_far',
            field=models.FloatField(default=0, verbose_name='Total amount of points amassed so far'),
        ),
        migrations.AlterField(
            model_name='result',
            name='users_tally',
            field=models.IntegerField(default=0, verbose_name='Total amount of times the quiz has been taken'),
        ),
    ]
